# Generated by Django 4.1.7 on 2023-04-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Sid', models.IntegerField(primary_key=True, serialize=False)),
                ('Sname', models.CharField(max_length=20)),
                ('Sage', models.IntegerField()),
                ('Semail', models.EmailField(max_length=254)),
                ('JDate', models.DateField()),
            ],
        ),
    ]
