# Generated by Django 4.1.7 on 2023-04-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='email',
            field=models.EmailField(default='webpage@.com', max_length=254),
        ),
    ]
