# Generated by Django 4.1.7 on 2023-04-04 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='sport',
            fields=[
                ('sport_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('no_of_players', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='players_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField()),
                ('pgender', models.CharField(max_length=100)),
                ('pname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.players')),
            ],
        ),
        migrations.AddField(
            model_name='players',
            name='sport_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.sport'),
        ),
    ]
