# Generated by Django 4.1.7 on 2023-04-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='id',
        ),
        migrations.AlterField(
            model_name='players',
            name='pname',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
