# Generated by Django 4.1.7 on 2023-04-03 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='institute',
            fields=[
                ('institute_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='trainers_data',
            fields=[
                ('trainer_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('trainer_sal', models.IntegerField()),
                ('trainer_DOB', models.DateField()),
                ('institute_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.institute')),
            ],
        ),
        migrations.CreateModel(
            name='trainer_sal_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_month_sal', models.IntegerField()),
                ('trainer_year_sal', models.IntegerField()),
                ('trainer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.trainers_data')),
            ],
        ),
    ]
