# Generated by Django 4.1.7 on 2023-04-01 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movies',
            fields=[
                ('movie_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('movie_rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='actors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero', models.CharField(max_length=100)),
                ('heroine', models.CharField(max_length=100)),
                ('movies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.movies')),
            ],
        ),
    ]
